# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import capture_pb2 as capture__pb2


class ScreenAnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeScreen = channel.unary_unary(
                '/capture.ScreenAnalyzer/AnalyzeScreen',
                request_serializer=capture__pb2.ScreenCapture.SerializeToString,
                response_deserializer=capture__pb2.AnalysisResult.FromString,
                )


class ScreenAnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeScreen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScreenAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeScreen,
                    request_deserializer=capture__pb2.ScreenCapture.FromString,
                    response_serializer=capture__pb2.AnalysisResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'capture.ScreenAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScreenAnalyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/capture.ScreenAnalyzer/AnalyzeScreen',
            capture__pb2.ScreenCapture.SerializeToString,
            capture__pb2.AnalysisResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
