# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capture.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcapture.proto\x12\x07\x63\x61pture\"[\n\rScreenCapture\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0f\n\x07mission\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x12\n\ninput_hash\x18\x04 \x01(\t\"g\n\x0e\x41nalysisResult\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x14\n\x0cis_duplicate\x18\x02 \x01(\x08\x12\x13\n\x0boutput_hash\x18\x03 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x04 \x01(\x03\x32R\n\x0eScreenAnalyzer\x12@\n\rAnalyzeScreen\x12\x16.capture.ScreenCapture\x1a\x17.capture.AnalysisResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'capture_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCREENCAPTURE']._serialized_start=26
  _globals['_SCREENCAPTURE']._serialized_end=117
  _globals['_ANALYSISRESULT']._serialized_start=119
  _globals['_ANALYSISRESULT']._serialized_end=222
  _globals['_SCREENANALYZER']._serialized_start=224
  _globals['_SCREENANALYZER']._serialized_end=306
# @@protoc_insertion_point(module_scope)
